### ISSUE TITLE
Default config.yaml file location is not an absolute path

### ISSUE THREAD

**Issue by willemw12** [deadc0de6/dotdrop#108] opened 2019-03-23 13:55 UTC
Note: ignoring the submodules, bootstrap.sh, dotdrop.sh and alias parts mentioned in the README.

The default config.yaml file location is the current working directory:

    $ cd
    $ dotdrop listfiles
    [ERR] Config format error: config file does not exist: config.yaml

Expected the default config.yaml location to be, for example, ~/.config/dotdrop/ (XDG specification).

**Comment by deadc0de6** [comment] 2019-03-23 16:06
Good point!
I have updated dotdrop, it will look in following places for its config file (unless specified)

* current/working directory or the directory where `dotdrop.sh` is located if used
* `${XDG_CONFIG_HOME}/dotdrop/`
* `~/.config/dotdrop/`

[The doc](https://github.com/deadc0de6/dotdrop/wiki/config#config) has been updated.

This is currently only available in the master branch.

**Comment by willemw12** [comment] 2019-03-23 17:37
The first bullet point is for backwards compatibility?

**Comment by deadc0de6** [comment] 2019-03-23 18:03
Well using dotdrop [as a submodule](https://github.com/deadc0de6/dotdrop/wiki/installation#as-a-submodule), i.e. with the `dotdrop.sh` script, is not considered a legacy way of doing. It is the recommended way if you want to have your dotfiles and the tool to manage it available from the same repository.

So not really for backwards compatibility as this first bullet point allows people using dotdrop as a submodule to have their config file directly located in the same directory as the `dotdrop.sh` script.

If you use dotdrop from a package (aur, pypi) you now have multiple ways (explicit or implicit) to specify the config file to use.

**Comment by willemw12** [comment] 2019-03-29 08:29
Can you make it `/etc/dotdrop` instead of `~/.config/dotdrop/` for the root user?

**Comment by deadc0de6** [comment] 2019-03-29 09:13
Defining the environment variable `DOTDROP_CONFIG` is not possible?

see <https://github.com/deadc0de6/dotdrop/wiki/usage#environment-variables>

**Comment by willemw12** [comment] 2019-03-29 09:54
Yes, I can do this in a script:

    if [ "$(id -ru)" -eq 0 ]; then
      CONFIGDIR="/etc/dotdrop"
    #else
    #  CONFIGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotdrop"
    fi
    ...

But you don't have to use `DOTDROP_CONFIG` now or a dotdrop wrapper script, if you don't want to. So it would be nice if dotdrop checks for /etc/dotdrop/config.yaml when running as root.

However, if this functionality does not belong in dotdrop, then please ignore my request.

**Comment by deadc0de6** [comment] 2019-03-29 10:34
Ok, I'll add a new directory to search for. What about adding it in the list instead of replacing the `~/.config/dotdrop/`, thus ending up with something like this:


* current/working directory or the directory where `dotdrop.sh` is located if used
* `${XDG_CONFIG_HOME}/dotdrop/`
* `~/.config/dotdrop/`
* `/etc/dotdrop/`

Would that work for you?

**Comment by willemw12** [comment] 2019-03-29 10:42
That's the correct solution. Either:

    /etc/xdg/dotdrop
    /etc/dotdrop

or

    /etc/xdg/dotdrop

would work.

**Comment by deadc0de6** [comment] 2019-03-29 13:54
Both `/etc/xdg/dotdrop` and `/etc/dotdrop` have been added, see [the doc](https://github.com/deadc0de6/dotdrop/wiki/config#config).
Let me know if you give it a try, thanks!

**Comment by willemw12** [comment] 2019-03-29 17:28
Does not find config.yaml.
Error message only mentions the last path (/etc/dotdrop). Does not mention whether or not it checks the other paths (/etc/xdg/dotdrop/, etc.).

For example, as root:

    $ ls /etc/xdg/dotdrop/config.yaml
    /etc/xdg/dotdrop/config.yaml
    $ sudo dotdrop compare
    [ERR] Config format error: config file does not exist: /etc/dotdrop/config.yaml

The config.yaml is a valid file. No error when it is located in /etc/dotdrop/.

Using the latest dotdrop-git (0.26.1.r18.gaefc6c3-1).

**Comment by deadc0de6** [comment] 2019-03-29 18:25
I'm unable to reproduce your issue:
```bash
$ cd /tmp
$ git clone https://github.com/deadc0de6/dotdrop.git; cd dotdrop
$ git rev-parse HEAD
aefc6c398f0903547fe7825ec11279f1c6fdcb8a
$ sudo mkdir -p /etc/xdg/dotdrop
$ sudo mv config.yaml /etc/xdg/dotdrop/
$ ./dotdrop.sh compare
[WARN] no dotfile defined for this profile ("hostname")
$ ./dotdrop.sh compare -V 2>&1 | grep confpath
[DEBUG][dotdrop.options._print_attr] - confpath: "/etc/xdg/dotdrop/config.yaml"
```

Could you run the same command with the `-V --verbose`?

**Comment by willemw12** [comment] 2019-03-29 18:55
My commands:

    + ls /etc/xdg/dotdrop/config.yaml
    /etc/xdg/dotdrop/config.yaml
    + sudo dotdrop compare -V
    [DEBUG][dotdrop.options.__init__] config file: /etc/dotdrop/config.yaml
    [ERR] Config format error: config file does not exist: /etc/dotdrop/config.yaml

My config.yaml:

    config:
      backup: false
      banner: false
      create: true
      dotpath: dotfiles
      ignoreempty: false
      keepdot: true
      link_by_default: false
      longkey: true
      showdiff: true
    dotfiles:
      f_etc_bash.bashrc:
        dst: /etc/bash.bashrc
        src: etc/bash.bashrc
    profiles:
      host1:
        dotfiles:
        - f_etc_bash.bashrc

Same error with the config.yaml from git clone.

Your commands:

    + cd /tmp
    + git clone https://github.com/deadc0de6/dotdrop.git
    Cloning into 'dotdrop'...
    + cd dotdrop
    + git rev-parse HEAD
    d6c4377decec1166ccc1c7a417abac20d15622fd
    + sudo mkdir -p /etc/xdg/dotdrop
    + sudo mv config.yaml /etc/xdg/dotdrop/
    + ./dotdrop.sh compare
    ...
    + grep confpath
    + ./dotdrop.sh compare -V
    [DEBUG][dotdrop.options._print_attr] - confpath: "/home/willem/.config/dotdrop/config.yaml"

Removed "/home/willem/.config/dotdrop/config.yaml":

    + cd /tmp
    + git clone https://github.com/deadc0de6/dotdrop.git
    Cloning into 'dotdrop'...
    + cd dotdrop
    + git rev-parse HEAD
    d6c4377decec1166ccc1c7a417abac20d15622fd
    + sudo mkdir -p /etc/xdg/dotdrop
    + sudo mv config.yaml /etc/xdg/dotdrop/
    + ./dotdrop.sh compare
    [WARN] no dotfile defined for this profile ("host1")
         _       _      _
      __| | ___ | |_ __| |_ __ ___  _ __
     / _` |/ _ \| __/ _` | '__/ _ \| '_ |
     \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.26.1
                                   |_|

    + grep confpath
    + ./dotdrop.sh compare -V
    [DEBUG][dotdrop.options._print_attr] - confpath: "/etc/xdg/dotdrop/config.yaml"

**Comment by deadc0de6** [comment] 2019-03-29 19:03
Could you do a `ls -l` and a `file` on both `/etc/xdg/dotdrop/config.yaml` and `/etc/dotdrop/config.yaml`?
Is dotdrop some alias? It seems it has only issues when you use `sudo` as you were able to successfully reproduce my example.

**Comment by willemw12** [comment] 2019-03-29 19:25
Very good find. I had a script `~/bin/dotdrop` as an alternative for this issue:

    if [ "$(id -ru)" -eq 0 ]; then
      CONFIGDIR="/etc/dotdrop"
    else
      CONFIGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotdrop"
    fi

    CONFIG="$CONFIGDIR/config.yaml"

    /usr/bin/dotdrop --cfg="$CONFIG" "$@"

Sorry about that. I have removed the script. Now no more errors.

Another thing, starting with an initial config:

    $ sudo dotdrop import /etc/bash.bashrc

This generates `workdir: ~/.config/dotdrop` in the conf file. This is not correct (for root).
I expected it to be the path to the config file that was found (dirname of the found config file: /etc/xdg/dotdrop or /etc/dotdrop).

**Comment by deadc0de6** [comment] 2019-03-29 19:41
Well `~/.config/dotdrop` is the default value for *workdir* if not specified. For root that would be `/root/.config/dotdrop` after resolving `~`. You can of course change that in the config file (path is either absolute or relative to the config file location). 

Is it an issue to change that in the config?

**Comment by deadc0de6** [comment] 2019-03-29 19:45
TBH I'd rather not have two defaults (one of any user and one for root) as there's already the possibility to change it right in the config file. Knowing also that this default is gonna be set at the beginning but one will usually edit the config to set some specific settings.

**Comment by willemw12** [comment] 2019-03-29 20:07
It can be left ~/.config/dotdrop.

`workdir` is only for accessing templates (according to the wiki)? They won't be accessible to normal users, while config.yaml and the dotfiles folder in /etc/... are accessible to normal users. Is that OK?

**Comment by deadc0de6** [comment] 2019-03-29 21:06
That's right `workdir` is used to symlink templates.
Not sure to understand your question though, what do you mean with *normal* users?

**Comment by willemw12** [comment] 2019-03-29 21:13
non-root users.

**Comment by deadc0de6** [comment] 2019-03-29 21:27
Well the access to directories and files is not managed by dotdrop but by the unix rights you set to the different directories and files.

If you are trying to store your user's dotfiles globally on the system in `/etc/`, you might want to have a look at [this doc](https://github.com/deadc0de6/dotdrop/wiki/global-config-files).

**Comment by deadc0de6** [comment] 2019-03-29 21:36
Or if you want to make sure, you can always edit the entry `workdir` in your config file and make it point to a directory where the rights are aligned with your use-case.

**Comment by willemw12** [comment] 2019-03-29 21:49
Don't think now that storing files in /root is an issue.

For the non-root user: using dotdrop together with git, it is git that is the central location, not /etc/... (and /root which won't be accessible in any case).

Have not really considered running as root use-case yet. For example, how to distribute the dotfiles between hosts (git clone with ssh by a non-root user, means the repo should not contain "secret" files).

**Comment by deadc0de6** [comment] 2019-03-29 22:07
Dotdrop provides some solutions for dealing with *secrets*: <https://github.com/deadc0de6/dotdrop/wiki/sensitive-dotfiles>

**Closed** 2019-03-30 07:17 UTC

**Comment by willemw12** [comment] 2019-04-14 06:32
Just for information. Don't have to change dotdrop.
Here is another way of finding the config file in one of the XDG folders or in /etc/dotdrop/:

    import xdg.BaseDirectory

    CONFIG_RESOURCE = "dotdrop/config.yaml"
    config_file = xdg.BaseDirectory.load_first_config(CONFIG_RESOURCE) or "/etc/" + CONFIG_RESOURCE                                                                      

Dependency: python3-xdg/python-xdg.

**Comment by deadc0de6** [comment] 2019-04-15 06:30
@willemw12 thanks for the info!
