### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#279] opened 2020-10-27 20:37 UTC
Dotdrop version (and git commit if run from source): v0.xxx
Using dotdrop: as a submodule, from pypi, '...'

**Describe the bug**
I think this is a bug.
I imported a group of .zsh* files to the dotfiles/ 
It showed up in the config.yaml file correctly
git add commit and push to remote repository
on another machine
git puil from remote repository
files downloaded
files do not show up in config.yaml

Not sure how to get the newly downloaded files into the config.yaml within the correct profile
I must me missing a step here which if I did it would not make this a bug.

Thanks.

**Steps to Reproduce**

1. Create a dotfile with content '...'
2. '...'

**Expected behavior**

**Additional information**

The relevant part of the config file
```yaml
config file content
```

Dotdrop's execution with the debug logs (`--verbose`)
```bash
$ dotdrop <cmd> --verbose ...
...
```

Any additional information that would help reproduce the bug.

**Comment by deadc0de6** [comment] 2020-10-29 19:12
This is not a bug as it is not related to dotdrop but to git. Are you sure you have versioned your config file along your dotfiles? In other words is your `config.yaml` among the file you committed and pushed (respectively pulled on the other side)?

**Closed** 2020-11-01 19:33 UTC
Labels: help
