### ISSUE TITLE
[help] importing a directory containing 1 or more symlinks

### ISSUE THREAD

**Issue by windowsrefund** [deadc0de6/dotdrop#184] opened 2019-08-23 17:59 UTC
Import is failing but I'm not sure why? By failing, I mean:

  * "[Err]" message is displayed after the attempt to import
  * The config.yaml is not changed (md5 sum still matches)
  * The directory I tried to import does exist in the dotfiles cache

I will certainly provide any information needed but for now, I'm not sure what my expectation should be.

**Comment by deadc0de6** [comment] 2019-08-24 12:14
I wasn't able to reproduce your issue, importing a directory containing a symlink did work:
```bash
$ mkdir /tmp/a
$ mkdir -p /tmp/a/b
$ echo 'test' > /tmp/a/b/c
$ touch /tmp/x
$ ln -s /tmp/x /tmp/a/x
$ tree /tmp/a                           
/tmp/a
├── b
│   └── c
└── x -> /tmp/x

1 directory, 2 files
$ ./dotdrop.sh import /tmp/a   
	-> "/tmp/a" imported
$ tree dotfiles       
dotfiles
└── tmp
    └── a
        ├── b
        │   └── c
        └── x

3 directories, 2 files
$ cat config.yaml                
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_a:
    src: tmp/a
    dst: /tmp/a
profiles:
  hostname:
    dotfiles:
    - d_a
```

Does the above work for you?

Please provide more information on your setup and the debug logs of dotdrop when importing the directory (`--verbose`), thanks!

**Comment by windowsrefund** [comment] 2019-08-25 16:08
Thanks for the reply. Not sure the above test is optimal as it links to an empty file. Perhaps this will better explain:

```
$ mkdir -p /tmp/a/b
$ echo test > /tmp/a/b/c
$ ln -s /tmp/a/b/c /tmp/a/x
$ tree /tmp/a
/tmp/a
├── b
│   └── c
└── x -> /tmp/a/b/c

1 directory, 2 files
$ dotdrop import /tmp/a
	-> "/tmp/a" imported
$ tree dotfiles/tmp
dotfiles/tmp/
└── a
    ├── b
    │   └── c
    └── x

2 directories, 2 files
$ test -L /tmp/a/x && echo is link
is link
$ test -L dotfiles/tmp/a/x && echo is link
$
```
So the import did not actually save a symlink. Instead, it created a copy of the file being linked to and saved it.

I think the above example shows the problem (or my flawed expectation?) well enough so I'm not going to flood with import's --verbose and more at this time.

**Comment by deadc0de6** [comment] 2019-08-25 16:41
I see, you were however talking about an `import` error in your initial post?

Regarding symlinks, dotdrop imports files by simply using a combination of `mkdir -p` and `cp -R -L` what means it will happily dereference symlinks and copy the destination (what you see with your example).

The current way of doing greatly simplifies the import and the installation of dotfiles. Handling symlinks would need much more logic on the `import` (as well as on the `install`) side.

May I ask what is your specific use-cases that would need to keep those symlinks?
Would you be ready to try yourself in implementing this?

**Comment by windowsrefund** [comment] 2019-08-25 16:48
Well, I want to maintain symlinks because... they're just as valid as another other type of file. I don't have a problem with dotdrop's handling of this (until it changes) but am fairly certain this is not made clear in the documentation.

As for coding involvement, I'll certainly take a peek under the hood as I really can't imagine this would be a big deal. Anyway, thanks for the discussion :)

**Comment by deadc0de6** [comment] 2019-08-25 17:00
Good point, I've added a line [in the wiki](https://github.com/deadc0de6/dotdrop/wiki/usage#import-dotfiles). They're indeed not invalid, but just need more care since dotdrop pivot files/directories back and forth of the `dotpath` directory.

It's not difficult per se but will introduce a few corner cases and some more logic. 
* Need to keep a logs for absolute symlinks (or re-symlink those back in the `dotpath` directory, and then revert that during installation).
* Need to process each file separately during `import` to decide if symlinks are relative, absolute or pointing outside of the imported directory for example.
* Need to handle a new *type* of file during installation (symlinks)
* What happens during installation if the destination of an absolute/relative symlinks outside the imported dir doesn't exist?
* etc

**Comment by windowsrefund** [comment] 2019-08-25 17:13
I've been looking at this in more detail and realize it's more complicated than I originally thought. Can't believe I've never needed to copy symlinks like this before. Oy!

**Comment by RedFlames** [comment] 2020-10-22 21:13
Hi, I ended up here because I accidentally imported a symlink with dotdrop and almost didn't realize what had happened.

I understand that you don't want to deal with importing & installing actual symlinks, but would you consider adding a warning or interactive prompt when a symlink gets detected?

I've actually just implemented it locally for myself like this near the top of `cmd_importer()` in `dotdrop.py`:
```python
        realdst = os.path.realpath(dst)
        if dst != realdst:
            # ask user
            msg = 'Real path \"{}\" \ndiffers from \"{}\", resolve symlinks and import anyways?'
            if not LOG.ask(msg.format(realdst,dst)):
                continue
```
(I thought about adding a LOG.warn, but I suppose LOG.ask already reflects the user's choice so nothing to warn about?)

I guess it might need a config flag that's something like `resolve_symlinks=always|never|ask`. I could try adding that as well and making a pull request, I reckon.

---
Also, thanks for creating dotdrop, @deadc0de6 :smiley: I like it so far!

**Comment by deadc0de6** [comment] 2020-10-23 06:17
So you actually would like to be warned (or have to ability to say no) when importing a symlink?

Sure I could add that, I would bind it to the `-f --force` cli option (without `-f --force` the user is queried for any symlink dereference).

What do you mean by 
> you don't want to deal with importing & installing actual symlinks

**Comment by RedFlames** [comment] 2020-10-23 09:32
Oh, I said that because earlier explained
> The current way of doing greatly simplifies the import and the installation of dotfiles. Handling symlinks would need much more logic on the `import` (as well as on the `install`) side.

Saying you "don't want to deal with" maybe wasn't correct, it's more that you don't see the use case for implementing all the logic to handle symlink import/install?

The change I'm suggesting isn't actually the same as what this ticket was about either, since it only applies to whether or not links are followed on import.

For the creation of symlinks by dotdrop, one possible step towards that functionality might be:
(adapted from windowsrefund's example from earlier)
```
[...]
$ tree /tmp/a
/tmp/a
├── b
│   └── c
└── x -> /tmp/a/b/c

$ dotdrop import --has-link=/tmp/a/x /tmp/a/b/c
	-> "/tmp/a/b/c" imported
```
and then add a new parameter in the config:
```
$ dotdrop files
f_c
    -> dst: /tmp/a/b/c
    -> src: [...]/dotdrop/dotfiles/a/b/c
    -> link: nolink
    -> custom_link: /tmp/a/x
```
This would restrict the creation of links to be tied to an actual imported file, but in this example a `dotdrop install` should then restore the tree as before, and should never create links that point to a missing file. 

Although even this solution would need some extra logic to check for the link during compare/update :thinking: And to error out on `import /tmp/a/x`... even this has edge cases. Oy vey.

And of course this still wouldn't quite work for the earlier example of just doing `import /tmp/a` above... unless you allow an arbitrary amount of links to be imported along the tree you're importing... and then you'd most definitely have the entire extra logic covered, eh :sweat_smile:

**Comment by deadc0de6** [comment] 2020-10-23 10:06
Oh I see, I should have re-read the upper part before answering ;-)

Well yes handling the import of symlinks brings its own problematic and corner cases and handling this is far from trivial. Dotdrop currently simply copies entire directory without having to deal with each specific files in it (is it a normal file, is it a relative link, is it an absolute link, is it a dead link, etc). Importing symlink is not such an issue but handling them during installation (is the symlink still pointing to an existing file, etc) and comparison can be quite complex to handle.

Regarding your feature request I see multiple ways to handle it:

* print a warning on import when a symlink is dereferenced and continue as normal
* ask the user if symlinks need to be followed (when `-f --force` is not provided) and ignore that file if the user enters *no*
* create a new config option like for example `import_follow_symlink` with multiple values possible (`yes`: the default will dereference symlink, `no`: ignore the file if it is a symlink)

Any of the above would be ok for you?

**Comment by RedFlames** [comment] 2020-11-05 20:58
Hey, sorry for not responding sooner, 
I'd say the second option is the most flexible for the user, yet also only needs like one or two lines changed. I actually implemented it that way for myself for now. ([I guess it was six new lines.](https://github.com/RedFlames/dotdrop/commit/b4d94ee8ce72fb587a99d22b34c8ee63e6b4919e))

Incidentally, I forked dotdrop and added another small feature I wanted, but I haven't looked into testing yet and am not sure if I should present the changes to you in a PR until I test it. (Or is a PR okay for discussing new features even when it's maybe not ready to be merged yet?)

**Comment by deadc0de6** [comment] 2020-11-05 21:17
Sure a PR is okay for discussing features. We can work the details together then and make sure it passes the tests.
I'll work on the symlinks thing in parallel, thanks for your input!

**Comment by deadc0de6** [comment] 2020-11-05 21:29
Second option implemented in above commit. Will be part of the next release.
Thanks for your help!

**Closed by deadc0de6** 2020-11-05 21:29 UTC
Labels: help

**Comment by deadc0de6** [comment] 2020-11-08 14:23
@RedFlames new version 1.3.7 released with above feature.
